### ISSUE TITLE
"Running" steps from readme don't work on Ubuntu 14.04.04

### ISSUE THREAD

**Issue by nazarov-yuriy** [yandex/porto#22]
On Ubuntu 14.04.04 portod launched in a way that is described in Readme(sudo portod &), tries to mount net_cls cgroup subsystem during startup:
```
[pid  4636] access("/sys/fs/cgroup/net_cls", F_OK) = -1 ENOENT (No such file or directory)
[pid  4636] mkdir("/sys/fs/cgroup/net_cls", 0755) = 0
[pid  4636] gettid()                    = 4636
[pid  4636] write(3, "2016-04-21 00:46:49 portod-slave"..., 102) = 102
[pid  4636] mount("cgroup", "/sys/fs/cgroup/net_cls", "cgroup", 0, "net_cls") = -1 ENOENT (No such file or directory)
```
without loading corresponding module cls_cgroup.
Of course, in a full Debian package module loading is implemented in yandex-porto.upstart script.
Maybe it should be documented in F.A.Q. of some kind.

**Comment by koct9i** [comment]
Heh, this more complicated than looks. In older kernels net_cls cgroup was in module cls_cgroup together with filter which use it. Later cgroup was separated and built into the kernel. And rtnl operaion loads module cls_cgroup when needed. So in modern kernels all works automatically. But for older kernels code that mounts cgroup should try to load module if cgroups is not found.

**Comment by koct9i** [comment]
done
