### ISSUE TITLE
Creating volume with native storage backend and disk quota fails

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#34]
Creating volume with native storage backend and disk quota fails with:

`Can't create volume: NotSupported:(Function not implemented: Cannot enable quota)`

**Comment by koct9i** [comment]
for upstream kernel you have to enable project quota for ext4  used for /place -- tune2fs -Q ...
probably xfs will work too

**Comment by s3rj1k** [comment]
can confirm that project quota works with xfs if FS is mounted with prjquota option.

space information is available from `portoctl vlist -v` or from `xfs_quota -x -c 'report -h -p' /place/porto_volumes/bionic`

would be nice to see names instead of project ids in output of xfs_quota

current output of `xfs_quota` for volume created with:
`portoctl vcreate /place/porto_volumes/bionic backend=native storage=/place/porto_storage/bionic space_limit=256M`

> Project quota on /place/porto_volumes/bionic (/dev/md3)
>                         Blocks              
> Project ID         Used   Soft   Hard Warn/Grace   
> --------------------------------------------------------------
> #0                     4.0G      0        0       00 [------]
> #2147487136 300.4M 0    256M   00 [-none-]

can you hint on docs that describe projectquota administration for ext4?

**Comment by koct9i** [comment]
project quota identified by number, xfs tools keep mapping name <-> id somewhere in /etc/
porto use higher half (>2^31) to avoid conflict with common users

> portoctl vcreate /place/porto_volumes/bionic backend=native storage=/place/porto_storage/bionic space_limit=256M
storage for "persistent" volume should differ from volume path.
or omitted -- temporary data will be stored in /place/porto_volumes/... like: portoctl vcreate -A space_limit=256M

ext4 implements the same interface as xfs, thus xfs tools should work too

**Comment by koct9i** [comment]
> how do I when match porto mapped ids to pretty names?
Currently there is no way to map id back to name or path.
Porto calculates quota id from directory inode number.

> does EXT4 enforce quota?
Should be. but due this bug in ext4 statfs shows wrong usage https://patchwork.kernel.org/patch/10196455/
Also for ext4 root user (with CAP_SYS_RESOURCE) ignore quota limit.
