### ISSUE TITLE
offstream kernel feature?

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#36]
What are those patches that man talks about?

Are they available as open-source?

**Comment by koct9i** [comment]
Some features are not implemented in standard upstream kernel, most of these patches are ad-hoc dirty hacks.
Some patchsets were published, at least fsio (fs level io limit) and cpu reserves (cpu_guarantee)
trivial oom kill counter was accepted into upstream

**Comment by s3rj1k** [comment]
Am i correct in thinking that fsio (fs level io limit) can limit io per path(porto volume)?

**Comment by koct9i** [comment]
nope, this is per memory cgroup limit. originally designed as next generation iolimit for openvz. ultimate hackery under the hood.

**Comment by koct9i** [comment]
kind of https://lkml.org/lkml/2015/1/15/619
design of dirty set controller was partially adopted into upstream, the rest pieces are not
