### ISSUE TITLE
LXCFS with porto

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#37]
Can this be somehow accomplished? 

so /proc in CT would show correct values limited by cgroups

**Comment by koct9i** [comment]
nope, this never happens

**Comment by s3rj1k** [comment]
is there any road map for implementing correct:

> 
> /proc/cpuinfo
> /proc/diskstats
> /proc/meminfo
> /proc/stat
> /proc/swaps
> /proc/uptime

inside CT

**Comment by koct9i** [comment]
they are correct. container is not a virtual machine.

**Comment by s3rj1k** [comment]
still openvz does that, lxd does that, provided that ct in porto uses virt_mode=os, porto also shoud fixup /proc

**Comment by koct9i** [comment]
I know. I've written some of this for openvz. As you could see it's on the death row now, lxc doesn't seems good too. So, these hacks are bad for your health =)

**Comment by s3rj1k** [comment]
what does not kill us, makes us stronger ;)

this hacks would actually improve adaptation of porto, all of other main features all ready implemented.

this could be made as optional addon
