### ISSUE TITLE
non exclusive cpusets?

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#39]
is it possible to some how over-commit cpusets?

**Comment by s3rj1k** [comment]
or a way to evenly distribute available cpus using

portoctl set bionic cpu_set '1,2'
portoctl set bionic2 cpu_set '3,4'
...

**Comment by koct9i** [comment]
You could distribute them manually. But this makes no sense for me.

**Comment by s3rj1k** [comment]
Ok, a little bit history to why this is needed.

I've managed to use lxcfs with porto, it actually works great and super simple to setup.

For limiting CPU num in CT and actually see this limit in pseudo /proc by lxcfs, I needs to setup cpu affinity.

To make this non exclusive I need to distribute affinity manually between CTs.

This is somewhat undesired, eventually this will skew load on host cpus, would be nice to have this option inside porto.

**Comment by s3rj1k** [comment]
this is what actually LXD does
https://github.com/lxc/lxd/blob/master/doc/containers.md#cpu-limits

**Comment by koct9i** [comment]
without runtime load balancing this scheme cannot handle cpu usage bursts effectively if cpu limits are overcommitted.

**Comment by s3rj1k** [comment]
so why this can't be implemented inside porto runtime?
