### ISSUE TITLE
persistent CTs?

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#40]
how can I create persistent over host node reboot CTs with virt_mode=os ?

**Comment by koct9i** [comment]
nope, porto is a backend. you have to write own launcher

**Comment by koct9i** [comment]
portod dump is a debug feature. persistence should be in separate service or tool.

**Comment by s3rj1k** [comment]
are there any plans on implementing this as open-source?

**Comment by koct9i** [comment]
We have plenty of them. I have no plans for yet another just for open-source.
