### ISSUE TITLE
portoctl create vs portoctl run different capabilities

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#42]
in CT created by `portoctl run virt_mode=os`:

caps:

> CHOWN; 
> DAC_OVERRIDE; 
> FOWNER; 
> FSETID; 
> KILL; 
> SETGID; 
> SETUID; 
> SETPCAP; 
> NET_BIND_SERVICE;
> NET_ADMIN; 
> NET_RAW; 
> IPC_LOCK; 
> SYS_CHROOT; 
> SYS_PTRACE; 
> SYS_BOOT; 
> MKNOD; 
> AUDIT_WRITE;
> SETFCAP

in CT created by `portoctl create`:

> CHOWN;
> DAC_OVERRIDE;
> FOWNER;
> FSETID;
> KILL;
> SETGID;
> SETUID;
> SETPCAP;
> LINUX_IMMUTABLE;
> NET_BIND_SERVICE;
> NET_ADMIN;
> NET_RAW;
> IPC_LOCK;
> SYS_CHROOT;
> SYS_PTRACE;
> SYS_ADMIN;
> SYS_BOOT;
> SYS_NICE;
> SYS_RESOURCE;
> MKNOD;
> AUDIT_WRITE;
> SETFCAP

additional caps in porto create CT:

> LINUX_IMMUTABLE;
> SYS_ADMIN;
> SYS_NICE;
> SYS_RESOURCE;

is this expected?

**Comment by koct9i** [comment]
caps depends on owner_user - see manpage
