### ISSUE TITLE
Map UID of processes to upper numbers (+100000)

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#44]
Is there any way of doing what lxc does with their unprivileged CTs?

mapping all process UID to 100000-165536

https://stgraber.org/2014/01/17/lxc-1-0-unprivileged-containers/

**Comment by koct9i** [comment]
user-ns support in porto is not planned

**Comment by s3rj1k** [comment]
@koct9i any changes on this design decision? 
https://youtu.be/izzXq7oe-3Q?t=201

**Comment by koct9i** [comment]
I've passed this project to another team. It seems they have no plans for any active development yet.

**Comment by s3rj1k** [comment]
That's a shame, thanks for info.
