### ISSUE TITLE
hooks support?

### ISSUE THREAD

**Issue by s3rj1k** [yandex/porto#47]
custom hooks support?

**Comment by koct9i** [comment]
we have sub-containers for that

**Comment by s3rj1k** [comment]
can you elaborate? usage example?

i was interested in running some external commands in different life stages of CT, just like LXC hooks

**Comment by koct9i** [comment]
just run sub-container ct/subct with properties command=".." isolate=false
this will start command in same environment and you could track
portoctl shell is done in the same way
